server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka1.com:7997/eureka/,http://eureka2.com:7998/eureka/,http://eureka3.com:7999/eureka/